[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "cancun"
fuzz = { runs = 10000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10000
out = "out"
script = "script"
solc = "0.8.29"
src = "src"
test = "tests"
libs = ["node_modules", "lib"]
extra_output = ["storageLayout", "metadata"]
ignored_error_codes = [2072]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@openzeppelinV4/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelinV4/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "solady/=lib/solady/src/",
    "@prb/math/=lib/prb-math/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "permit2/=lib/permit2/src/",
    "contracts/=intuition-contracts-v2-periphery/contracts/"
]